### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by oxydedefer** [collective/collective.z3cform.mapwidget#7]
@gborelli Could you make a new release  on pypi please :)

**Comment by laulaz** [comment]
@davidjb @maethu: could you maybe help on this one ?

**Comment by davidjb** [comment]
I haven't used this in a long while but if someone else wants maintainer access, I'll assign it accordingly on PyPI.  Just let me know.

**Comment by maethu** [comment]
I can make one!

**Comment by maethu** [comment]
Done 😊

**Comment by laulaz** [comment]
Thanks a lot @maethu !

**Comment by oxydedefer** [comment]
Thanks  @maethu  :)
